### ISSUE TITLE
OMC log file cannot be created if OpenModelica is running

### ISSUE THREAD

**Issue by CSchoel** [THM-MoTE/mope-server#8]
Mo|E (or the OMC?) tries to create the log `C:\Users\Username\AppData\Local\Temp\omc_home\omc.log` which is already in use if an OMC instance is running that was started by OpenModelica. This causes the server to hang up on the connection to the Atom-plugin.

Tested with OpenModelica version 1.13.0 and Mo|E version 0.6.5.

**Comment by njustus** [comment]
Related to #9 .. 
Either we are generating a random log file name, or parsing the output so we don't need a log file anymore. May be we should parse the omc stdout and write them into our log file with a specific logger :thinking:
